name: Docker Build
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: build the image
        run: |
          docker buildx build --tag pnaro/postgis:13-3.1 --push --platform \
          linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6 \
          13-3.1/alpine/  

